# Generated by Django 4.1.7 on 2023-03-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='directores',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('edad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='peliculas',
            fields=[
                #('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.directores')),
            ],
        ),
    ]
